---
title: "Untitled"
output: html_document
---

```{r, warning = FALSE, message = FALSE, include = FALSE}
#load in specific data
date <- "08-Dec-2017"
monkey <- "Ulysses"

search_string <- paste0(date, ".*", monkey, "COMPACT")

#find all data files
data_files <- dir("../savefiles")

#load in the relevant data
specific_files <- data_files[grep(search_string, data_files)]
task_data <- rbindlist(lapply(paste0("../savefiles/", specific_files), read.csv, na.strings = "NaN"), idcol = "block") %>%
  #munge the data
  .[, block := paste("block", block)] %>%
  .[, trial:= 1:.N, block] %>%
  .[bundle_position == 1, bundle_distance := (monkey_final_bid + 1)/2] %>%
  .[bundle_position == 0, bundle_distance := (1-monkey_final_bid)/2] %>%
  .[bundle_distance < 1, fractal_bid := 1] %>%
  .[bundle_distance > 1, fractal_bid := 0] %>%
  .[, offer_ml := paste0(((offer_value*2)-1) * 0.15, "ml")]

```

```{r, warning = FALSE, message = FALSE}
#plot the left vs right choices of the monkey
p1 <- ggplot(data = task_data, aes(x = monkey_final_bid, y = bundle_position)) +
  geom_point(alpha = 0.4, aes(colour = trial, size = offer_value, shape = fractal_bid)) +
  scale_colour_continuous(low = "blue", high = "red", name = "trial number") +
  scale_size_continuous(range = c(4,6), name = "juice offered") +
  scale_shape_manual(values = c(15,16), name = "juice chosen") +
  xlab("bid position") +
  ylab("fractal position") +
  annotate("text", label = "left bid", x = -0.5, y = 0.45, size = 7, colour = "darkgrey") +
  annotate("text", label = "right bid", x = 0.5, y = 0.45, size = 7, colour = "darkgrey") +
  ggtitle("Monkey Bid Positions on Binary Choice Task",
          subtitle = paste(date, ";", monkey, ";", length(unique(data$block)), "blocks")) +
  #theme_fivethirtyeight() +
  theme(strip.text.x = element_text(size = 14)) +
  theme(axis.title.x = element_text(size = 14)) +
  theme(axis.title.y = element_text(size = 14)) +
  facet_wrap("block")

p1
```

```{r, warning = FALSE, message = FALSE, include = FALSE}
#gather the data with respect the the distance from the bundle that the monkey bid
#plot the monkeys bundle distance against all other variables
p1 <- ggplot(data = task_data, aes(x = bundle_distance, y = bundle_position)) +
  geom_point(alpha = 0.4, aes(colour = trial, size = offer_value, shape = fractal_bid)) +
  scale_colour_continuous(low = "blue", high = "red", name = "trial number") +
  scale_size_continuous(range = c(4,6), name = "juice offered") +
  scale_shape_manual(values = c(15,16), name = "juice chosen") +
  xlab("bid position") +
  ylab("fractal position") +
  annotate("text", label = "left bid", x = -0.5, y = 0.45, size = 7, colour = "darkgrey") +
  annotate("text", label = "right bid", x = 0.5, y = 0.45, size = 7, colour = "darkgrey") +
  ggtitle("Monkey Bid Positions on Binary Choice Task",
          subtitle = paste(date, ";", monkey, ";", length(unique(data$block)), "blocks")) +
  #theme_fivethirtyeight() +
  theme(strip.text.x = element_text(size = 14)) +
  theme(axis.title.x = element_text(size = 14)) +
  theme(axis.title.y = element_text(size = 14)) +
  facet_wrap("block")

p1

```


