---
title: "BDM Task Analysis Pipeline"
output:
  html_document: default
  pdf_document: default
---

```{r, message = FALSE, warning = FALSE, include = FALSE}
#libraries
library(tidyverse)
library(data.table)
library(ggthemes)
#library(R.matlab)
```

```{r, message = FALSE, warning = FALSE, include = FALSE}
#savefile directory
setwd("C:/Users/WS-Guest/Desktop/MATisse/savefiles")
#setwd("C:/Users/Alaa/Desktop/MATisse/savefiles")

#load in specific data
date <- "08-Dec-2017"
monkey <- "Ulysses"

search_string <- paste0(date, ".*", monkey, "COMPACT")

savefiles <- dir()

files <- savefiles[grep(search_string, savefiles)]
data <- rbindlist(lapply(files, read.csv, na.strings = "NaN"), idcol = "block") %>%
  .[, block := paste("block", block)] %>%
  .[, trial:= 1:.N, block]

```

```{r, message = FALSE, warnin = FALSE}
print("Parameters:")
date
monkey
```

```{r, message = FALSE, warning = FALSE, include = FALSE}
data[bundle_position == 1, bundle_distance := monkey_final_bid + 1][bundle_position == 0, bundle_distance := 1-monkey_final_bid] %>%
  .[bundle_position == 1, bundle_pos_char := "left"] %>%
  .[bundle_position == 0, bundle_pos_char := "right"] %>%
  .[bundle_distance < 1, fractal_bid := "Y"] %>%
  .[bundle_distance > 1, fractal_bid := "N"] %>%
  .[, offer_ml := paste0(((offer_value*2)-1) * 0.15, "ml")]

#plot the left vs right choices of the monkey
p1 <- ggplot(data = data, aes(x = monkey_final_bid, y = bundle_position)) +
  geom_point(alpha = 0.4, aes(colour = trial, size = offer_value, shape = fractal_bid)) +
  scale_colour_continuous(low = "blue", high = "red", name = "trial number") +
  scale_size_continuous(range = c(4,6), name = "juice offered") +
  scale_shape_manual(values = c(15,16), name = "juice chosen") +
  xlab("bid position") +
  ylab("fractal position") +
  annotate("text", label = "left bid", x = -0.5, y = 0.45, size = 7, colour = "darkgrey") +
  annotate("text", label = "right bid", x = 0.5, y = 0.45, size = 7, colour = "darkgrey") +
  ggtitle("Monkey Bid Positions on Binary Choice Task",
          subtitle = paste(date, ";", monkey, ";", length(unique(data$block)), "blocks")) +
  #theme_fivethirtyeight() +
  theme(strip.text.x = element_text(size = 14)) +
  theme(axis.title.x = element_text(size = 14)) +
  theme(axis.title.y = element_text(size = 14)) +
  facet_wrap("block")

```

Graph showing where the monkey has bid over time for each experimental block

```{r, message = FALSE, warning = FALSE}
p1
```

```{r, message = FALSE, warning = FALSE, include = FALSE}
model1 <- glm(data = data[offer_ml == "0.15ml"], bundle_position~monkey_final_bid, family = binomial)
model2 <- glm(data = data[offer_ml == "0.45ml"], bundle_position~monkey_final_bid, family = binomial)
model3 <- glm(data = data[offer_ml == "0.75ml"], bundle_position~monkey_final_bid, family = binomial)

fake_bids = seq(-1, 1, 0.1)

model_df <- data.frame(x = fake_bids,
                       ml0.15 = predict(model1, list(monkey_final_bid = fake_bids), type = "response"),
                       ml0.45 = predict(model2, list(monkey_final_bid = fake_bids), type = "response"),
                       ml0.75 = predict(model3, list(monkey_final_bid = fake_bids), type = "response")) %>%
  melt(., id = c("x")) #to plot in one line and use scale_alpha_cont

p2 <- ggplot(data = data, aes(x = monkey_final_bid, y = bundle_position)) +
  geom_point(alpha = 0.4, aes(size = offer_value, shape = fractal_bid)) +
  geom_line(data = model_df, aes(x = x, y = value, colour = variable), size = 2, alpha = 0.5) +
  scale_size_continuous(range = c(4,6), name = "juice offered") +
  scale_shape_manual(values = c(15,16), name = "juice chosen") +
  xlab("bid position") +
  ylab("fractal position") +
  annotate("text", label = "left bid", x = -0.5, y = 0.45, size = 7, colour = "darkgrey") +
  annotate("text", label = "right bid", x = 0.5, y = 0.45, size = 7, colour = "darkgrey") +
  ggtitle("Monkey Bid Positions on Binary Choice Task",
          subtitle = paste(date, ";", monkey, ";", length(unique(data$block)), "blocks")) +
  #theme_fivethirtyeight() +
  theme(strip.text.x = element_text(size = 14)) +
  theme(axis.title.x = element_text(size = 14)) +
  theme(axis.title.y = element_text(size = 14))
```

Graph showing regression of each offer value

```{r, message = FALSE, warning = FALSE}
p2
```
