---
title: "Experimental Plots"
output: html_document
---

```{r, warning = FALSE, message = FALSE, include = FALSE}
require(ggplot2)
require(ggthemes)
require(dplyr)
require(magrittr)
require(data.table)
require(tidyr)
require(tweenr)
require(gganimate)
require(R.matlab)
```

```{r, warning = FALSE, message = FALSE, include = FALSE}
# BINARY CHOICE DATA
#load in specific data
date <- "25-Jan-2018"
monkey <- "Ulysses"

search_string <- paste0(date, ".*", monkey, "COMPACT")
#find all data files
directory <- "C:/Users/WS-Guest/Desktop/task data/"
data_files <- dir(directory)

#load in the relevant data
specific_files <- data_files[grep(search_string, data_files)]
#specific_files <- specific_files[1:2]

task_data <- rbindlist(lapply(paste0(directory, specific_files), read.csv, na.strings = "NaN"), idcol = "block") %>%
  #munge the data
  .[, block := paste("block", block)] %>%
  .[, trial:= 1:.N, block] %>%
  .[is.na(task_failure), task_failure := "none"] %>%
  .[bundle_position == 1, bundle_distance := (monkey_final_bid + 1)/2] %>%
  .[bundle_position == 0, bundle_distance := (1-monkey_final_bid)/2] %>%
  .[bundle_distance < 0.5, fractal_bid := 1] %>%
  .[bundle_distance > 0.5, fractal_bid := 0] %>%
  .[, offer_ml := paste0(((offer_value*2)-1) * 0.15, "ml")] %>%
  .[, bundle_liquid := 1.2 - (bundle_water_perc * 1.2)]

mat <- readMat(paste0(directory, "testmat.mat"))
single_trial <- mat$x[[1]][[1]][[1]]

get_single_trial <- function(array, trial){
  num_string <- unlist(array$x[[1]][[1]][[trial]])
  nan_omit <- num_string[which(num_string != "NaN")]
  
  df <- data.frame(adjust = nan_omit,
                   trial = trial,
                   frame = 1:length(nan_omit))
  
  return(df)
}

key_stats <- setDT(task_data) %>%
  .[, list(trial, offer_value, bundle_liquid, bundle_position)]

joystick <- rbindlist(lapply(which(task_data$task_failure != "joystick_not_stationary"), get_single_trial, array = mat)) %>%
  setDT() %>%
  .[, x := cumsum(adjust), trial] %>%
  .[, plot_frame := (trial * 50 + frame) - 50] %>%
  .[key_stats, on = "trial"]

joystick2 <- joystick[1:500]

p2 <- ggplot(joystick2, aes(x=x, y=1, frame = plot_frame)) +
  geom_point(aes(colour = factor(offer_value), size = bundle_liquid)) 

gganimate(p2, filename="joystick.gif", title_frame = FALSE, interval = 0.05)

```

```{r, warning = FALSE, message = FALSE, include = FALSE}
p1 <- ggplot(data = task_data, aes(x = bundle_distance, y = 1)) +
  geom_point(alpha = 0.5, aes(size = factor(bundle_liquid), colour = factor(offer_value))) +
  scale_colour_manual(values = c("yellow", "purple", "blue")) +
  scale_size_manual(values = 1:10)
```
