---
title: "BDM Analysis"
author: "Robert Hickman"
date: "22 March 2018"
output: pdf_document
classoption: landscape
---

```{r libraries, warning = FALSE, message = FALSE, include = FALSE}
require(ggplot2)
require(ggthemes)
require(dplyr)
require(magrittr)
require(data.table)
require(tidyr)
require(extrafont)
library(zoo)

```

```{r which data, warning = FALSE, message = FALSE}
monkey <- "Vicer"
today <- "29-August-2018"
look_back <- "28-August-2018"

start_trial <- 0
stop_trial <- "all"

merge_days <- FALSE

```

```{r data_input, warning = FALSE, message = FALSE, include = FALSE}
if(!is.na(look_back)){
  #use a selected range of dates
  dates <- strftime(seq(as.Date(look_back, "%d-%b-%Y"), as.Date(today, "%d-%b-%Y"), "days"), "%d-%b-%Y")
} else {
  #else use the last week of data
  dates <- strftime(seq(as.Date(today, "%d-%b-%Y") -7, as.Date(today, "%d-%b-%Y"), "days"), "%d-%b-%Y")
}
#create a string to search for in the filename
search_string <- paste0(dates, ".*", monkey, "COMPACT")

#find all the relevant data files
###Obvs change for yours
directory <- "C:/Users/WS-Guest/Desktop/task data/"
data_files <- dir(directory)
###When comparing multiple days want to unlist (generally good to see progress rather than just one days data)
specific_files <- unlist(sapply(search_string, grep, x = data_files))

#load up all the files
for(file in 1:length(specific_files)){
  data <- read.csv(paste0(directory, dir(directory)[specific_files[file]]), stringsAsFactors = FALSE, na.strings = "NaN")
  #remove the pavlovian data files
  if(ncol(data) == 12){
    #load in the data and munge it around a bit
    BDM_data <- data %>%
      setDT() %>%
      .[,trial:= 1:.N] %>%
      .[,stimulus_trial := 1:.N, by = offer_value] %>%
      .[,block_no := file] %>%
      #get the date from the filename
      .[,date := as.Date(gsub(" .*", "", dir(directory)[specific_files[file]]), "%d-%b-%Y")]
    #merge into one df
    if(!exists('task_data')){
      task_data <- BDM_data
    }  else {
      task_data <- rbindlist(list(task_data, BDM_data)) %>%
        .[order(block_no, trial)]
    }
  }
}

if(merge_days){
  task_data <- task_data %>%
    .[, block_no := as.numeric(as.factor(date))] %>%
    .[, trial := 1:.N, by = block_no]
}

#reset the block nos
task_data$block_no <- as.numeric(as.factor(task_data$block_no))
task_data$task_failure <- gsub(" .*", "", task_data$task_failure)
task_data$task_failure <- factor(task_data$task_failure)

for(sub_block in 1:length(unique(task_data$block_no))){
  data_sub <- task_data[block_no == sub_block]
  for(sub_offer in 1:length(unique(data_sub$offer_value))){
    data_subbed <- data_sub[reward == sub_offer]
    
    row <- data.frame(block_no = sub_block,
                      offer_value = sub_offer,
                      juice_offered = max(unique(data_subbed$reward_liquid), na.rm = TRUE))
    if(sub_block == 1 & sub_offer == 1){
      merge_df <- row
    } else {
      merge_df <- rbind(merge_df, row)
    }
  }
}

#get the rolling meap4ns
#replace 10/width with correct_trials here for full rolling mean
task_data <- task_data %>%
  .[is.na(task_failure), correct_trials := 1:.N, by = c("offer_value", "date")] %>%
  .[is.na(task_failure), rolling_mean := rollapply(monkey_final_bid, mean, align = "right", width = correct_trials), by = c("offer_value", "date")] %>%
  .[is.na(task_failure), rolling_sd := rollapply(monkey_final_bid, sd, align = "right", width = correct_trials), by = c("offer_value", "date")] %>%
  .[, rolling_se := rolling_sd / sqrt(correct_trials)]

#get the actual amount of juice/water offered per trial
task_data <- merge(task_data, merge_df, by = c("block_no", "offer_value")) %>%
  #finally select and rearrange useful columns
  .[,c("date", "block_no", "trial", "juice_offered",
      "computer_bid", "monkey_final_bid", "adjust", "start_position",
      "win", "task_failure", "reward_liquid", "budget_liquid",
      "correct_trials", "rolling_mean", "rolling_sd", "rolling_se")] %>%
  setcolorder(., c("date", "block_no", "trial", "juice_offered",
                   "computer_bid", "monkey_final_bid", "adjust", "start_position",
                   "win", "task_failure", "reward_liquid", "budget_liquid",
                   "correct_trials", "rolling_mean", "rolling_sd", "rolling_se"))

#get rid of all the crap in the environment
rm(list = ls()[-c(grep("task_data", ls()),
                  grep("monkey", ls()),
                  grep("today", ls()),
                  grep("look_back", ls()),
                  grep("_trial", ls()))])

```
\newpage

```{r bid_headline_stats, warning = FALSE, message = FALSE, include = FALSE}
p1 <- ggplot(data = task_data, aes(y = monkey_final_bid, factor(juice_offered))) +
  #geom_violin(fill = "darkgrey") +
  geom_jitter(alpha = 0.5, width = 0.15, size = 3, aes(colour = trial)) +
  geom_boxplot(notch = TRUE, alpha = 0.7) +
  scale_colour_continuous(low = "darkred", high = "darkblue") +
  xlab("Offer Value (/ml)") +
  ylab("Final Bid Fraction") +
  ggtitle("Monkey Final Bids on BDM 2nd Price Task") +
  theme_minimal() +
  theme(strip.text.x = element_text(size = 14)) +
  theme(axis.title.x = element_text(size = 14)) +
  theme(axis.title.y = element_text(size = 14)) +
  facet_wrap(~date)

```

```{r p1_plot, warning = FALSE, message = FALSE, fig.width = 12, fig.height = 8}
p1

```
\newpage

```{r bid_movements, warning = FALSE, message = FALSE, include = FALSE}
p2 <- task_data %>%
  .[, c("trial", "monkey_final_bid", "start_position", "win", "juice_offered", "date", "adjust")] %>%
  .[, adjust := adjust / abs(adjust)] %>%
  .[adjust != "NaN"] %>%
  #melt.data.table(measure.vars = c("monkey_final_bid", "start_position")) %>%
  ggplot(data = ., aes(colour = factor(juice_offered))) +
  geom_segment(aes(linetype = factor(adjust), x = trial, xend = trial, y = start_position, yend = monkey_final_bid), arrow = arrow(length = unit(0.2, "cm"))) +
  #geom_line(size = 1.2) +
  scale_linetype_manual(values = c("solid", "dashed"), name = "Upwards Movement") +
  geom_point(aes(x = trial, y = start_position)) +
  xlab("Trial") +
  ylab("Trial Movement") +
  ggtitle("Monkey Bid Movement on BDM 2nd Price Task",
          subtitle = paste(monkey, ":", look_back, "-", today)) +
  theme_minimal() +
  theme(strip.text.x = element_text(size = 14)) +
  theme(strip.text.y = element_text(size = 14)) +
  theme(axis.title.x = element_text(size = 14)) +
  theme(axis.title.y = element_text(size = 14)) +
  facet_grid(factor(juice_offered)~date)

```

```{r plot_p2, warning = FALSE, message = FALSE, fig.width = 12, fig.height = 8}
p2

```
\newpage

```{r bid_rolling_means, warning = FALSE, message = FALSE, include = FALSE}
p3 <- task_data %>%
  .[is.na(task_failure)] %>%
  #.[, rolling_mean := na.locf(rolling_mean, na.rm = TRUE), by = c("block_no", "juice_offered")] %>%
  #.[, rolling_se := append(NA, na.locf(rolling_se, na.rm = TRUE)), by = c("block_no", "juice_offered")] %>%
  ggplot(., aes(x = trial, y = rolling_mean, group = factor(juice_offered))) +
  geom_line(aes(colour = factor(juice_offered)), size = 2) +
  geom_ribbon(aes(ymin = rolling_mean - rolling_se, ymax = rolling_mean + rolling_se, fill = factor(juice_offered)), alpha = 0.4) +
  geom_line(data = dplyr::filter(task_data, is.na(task_data$task_failure)), aes(x = trial, y = rolling_mean, group = factor(juice_offered), colour = factor(juice_offered))) +
  scale_fill_discrete(guide = FALSE) +
  scale_colour_discrete(name = "Reward Offered (ml)") +
  xlab("Task Trials") +
  ylab("Cumulative Mean Bid") +
  ggtitle("Monkey Mean Bids (+/- SE) on BDM 2nd Price Task") +
  theme_minimal() +
  theme(strip.text.x = element_text(size = 14)) +
  theme(strip.text.y = element_text(size = 14)) +
  theme(axis.title.x = element_text(size = 14)) +
  theme(axis.title.y = element_text(size = 14)) +
  facet_wrap(~date)


p3 <- task_data %>%
  .[is.na(task_failure)] %>%
  #.[, rolling_mean := na.locf(rolling_mean, na.rm = TRUE), by = c("block_no", "juice_offered")] %>%
  #.[, rolling_se := append(NA, na.locf(rolling_se, na.rm = TRUE)), by = c("block_no", "juice_offered")] %>%
  ggplot(., aes(x = trial, y = rolling_mean, group = factor(juice_offered))) +
  geom_line(aes(colour = factor(juice_offered)), size = 2) +
  geom_ribbon(aes(ymin = rolling_mean - rolling_se, ymax = rolling_mean + rolling_se, fill = factor(juice_offered)), alpha = 0.4) +
  geom_line(data = dplyr::filter(task_data, is.na(task_data$task_failure)), aes(x = trial, y = rolling_mean, group = factor(juice_offered), colour = factor(juice_offered))) +
  scale_fill_discrete(guide = FALSE) +
  scale_colour_discrete(name = "Reward Offered (ml)") +
  xlab("Task Trials") +
  ylab("Cumulative Mean Bid") +
  ggtitle("Monkey Mean Bids (+/- SE) on BDM 2nd Price Task") +
  theme_minimal() +
  theme(strip.text.x = element_text(size = 14)) +
  theme(strip.text.y = element_text(size = 14)) +
  theme(axis.title.x = element_text(size = 14)) +
  theme(axis.title.y = element_text(size = 14)) +
  facet_wrap(~date)

p3.5 <- task_data %>%
  .[is.na(task_failure)] %>%
  #.[, rolling_mean := na.locf(rolling_mean, na.rm = TRUE), by = c("block_no", "juice_offered")] %>%
  #.[, rolling_se := append(NA, na.locf(rolling_se, na.rm = TRUE)), by = c("block_no", "juice_offered")] %>%
  ggplot(., aes(x = correct_trials, y = rolling_mean, group = factor(juice_offered))) +
  geom_line(aes(colour = factor(juice_offered)), size = 2) +
  geom_ribbon(aes(ymin = rolling_mean - rolling_se, ymax = rolling_mean + rolling_se, fill = factor(juice_offered)), alpha = 0.4) +
  scale_fill_discrete(guide = FALSE) +
  scale_colour_discrete(name = "Reward Offered (ml)") +
  xlab("Correct Trials Per Fractal") +
  ylab("Cumulative Mean Bid") +
  ggtitle("Monkey Mean Bids (+/- SE) on BDM 2nd Price Task") +
  theme_minimal() +
  theme(strip.text.x = element_text(size = 14)) +
  theme(strip.text.y = element_text(size = 14)) +
  theme(axis.title.x = element_text(size = 14)) +
  theme(axis.title.y = element_text(size = 14)) +
  facet_wrap(~date)

```

```{r plot_p3, warning = FALSE, message = FALSE, fig.width = 12, fig.height = 8}
p3

p3.5
```
\newpage

```{r rowwise_welch_tests, warning = FALSE, message = FALSE, include = FALSE, eval = FALSE}
get_p_values <- function(low, high, data, hypotheses) {
  low_data <- data %>%
    .[juice_offered == low] %>%
    .[, c("monkey_final_bid")] %>%
    unlist()
  
  high_data <- data %>%
    .[juice_offered == high] %>%
    .[, c("monkey_final_bid")] %>%
    unlist()
  
  p <- t.test(low_data, high_data,
              alternative = "less", var.equal = FALSE, conf.level = 1 - (0.05 / hypotheses))$p.value %>%
    as.data.frame() %>%
    mutate(low = low, high = high)
  
  return(p)
}

get_trial_p_values <- function(data) {
  trial <- max(data$trial)
  date <- unique(data$date)
  
  data <- data %>%
    .[duplicated(juice_offered) | duplicated(juice_offered, fromLast = TRUE)]
  
  if(length(unique(data$juice_offered)) > 1) {
    offer_values <- data[[variable]] %>%
      unique() %>%
      sort() %>%
      combn(., m = 2)
    
    hypotheses <- ncol(offer_values)
    
    low_value <- offer_values[1,]
    high_value <- offer_values[2,]
    
    
    p_values <- mapply(get_p_values, low_value, high_value, MoreArgs = list(data = data, hypotheses = hypotheses)) %>%
      t() %>% as.data.frame() %>%
      select(p = ".", lower_offer = low, higher_offer = high) %>%
      mutate(trial = trial, date = date)
  } else {
    p_values <- data.frame(p = NA, lower_offer = NA, higher_offer = NA, trial = trial, date = date)
  }
  
  return(p_values)
}

get_date_p_values <- function(data) {
  date_p_values <- rbindlist(lapply(data, get_trial_p_values))
  return(date_p_values)
}

data <- task_data %>%
  .[is.na(task_failure)] %>%
  setorder(date, trial) %>%
  .[, trial := 1:.N, by = "date"] %>%
  .[, c("date", "trial", "juice_offered", "monkey_final_bid")] %>%
  split(.$date) %>%
  lapply(., function(data) Reduce(rbind, split(data, data$trial), accumulate=TRUE))

variable = "juice_offered"

all_p_values <- task_data %>%
  .[is.na(task_failure)] %>%
  setorder(date, trial) %>%
  .[, trial := 1:.N, by = "date"] %>%
  .[, c("date", "trial", "juice_offered", "monkey_final_bid")] %>%
  split(.$date) %>%
  lapply(., function(data) Reduce(rbind, split(data, data$trial), accumulate=TRUE)) %>%
  rbindlist(lapply(., get_date_p_values)) %>%
  .[!is.na(p)] %>%
  .[, comparison := paste0(all_p_values$lower_offer, "~", all_p_values$higher_offer)]

p4 <- ggplot(data = all_p_values, aes(x = trial, y = as.numeric(p))) +
  geom_line(aes(colour = comparison), size = 2, alpha = 0.5) +
  scale_color_viridis_d() +
  theme_minimal() +
  scale_y_log10() +
  xlab("trial") +
  ylab("log Welch test statistic") +
  facet_wrap(~date)

```

```{r plot_p4, warning = FALSE, message = FALSE, eval = FALSE, fig.width = 12, fig.height = 8}
p4

```


